# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 387)
        MainWindow.setStyleSheet("QPushButton:checked { background-color: rgb(85, 87, 83); }\n"
"QWidget {\n"
"    background-color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(85, 87, 83);    \n"
"    border-color: rgb(136, 138, 133);\n"
"    color: rgb(250,250,250);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_termostat = QtWidgets.QWidget()
        self.tab_termostat.setObjectName("tab_termostat")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_termostat)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lb_temp = QtWidgets.QLabel(self.tab_termostat)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(80)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_temp.setFont(font)
        self.lb_temp.setObjectName("lb_temp")
        self.horizontalLayout_2.addWidget(self.lb_temp)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_humidity = QtWidgets.QLabel(self.tab_termostat)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lb_humidity.setFont(font)
        self.lb_humidity.setObjectName("lb_humidity")
        self.horizontalLayout_3.addWidget(self.lb_humidity)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lb_temp_target = QtWidgets.QLabel(self.tab_termostat)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lb_temp_target.setFont(font)
        self.lb_temp_target.setObjectName("lb_temp_target")
        self.horizontalLayout_3.addWidget(self.lb_temp_target)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.pb_up = QtWidgets.QPushButton(self.tab_termostat)
        self.pb_up.setMinimumSize(QtCore.QSize(40, 50))
        self.pb_up.setObjectName("pb_up")
        self.verticalLayout_2.addWidget(self.pb_up)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pb_ac = QtWidgets.QPushButton(self.tab_termostat)
        self.pb_ac.setMinimumSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pb_ac.setFont(font)
        self.pb_ac.setCheckable(True)
        self.pb_ac.setChecked(False)
        self.pb_ac.setFlat(False)
        self.pb_ac.setObjectName("pb_ac")
        self.horizontalLayout_5.addWidget(self.pb_ac)
        self.pb_off = QtWidgets.QPushButton(self.tab_termostat)
        self.pb_off.setMinimumSize(QtCore.QSize(40, 50))
        self.pb_off.setCheckable(True)
        self.pb_off.setObjectName("pb_off")
        self.horizontalLayout_5.addWidget(self.pb_off)
        self.pb_heat = QtWidgets.QPushButton(self.tab_termostat)
        self.pb_heat.setMinimumSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pb_heat.setFont(font)
        self.pb_heat.setCheckable(True)
        self.pb_heat.setObjectName("pb_heat")
        self.horizontalLayout_5.addWidget(self.pb_heat)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.pb_down = QtWidgets.QPushButton(self.tab_termostat)
        self.pb_down.setMinimumSize(QtCore.QSize(40, 50))
        self.pb_down.setObjectName("pb_down")
        self.verticalLayout_2.addWidget(self.pb_down)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pb_manual = QtWidgets.QPushButton(self.tab_termostat)
        self.pb_manual.setMinimumSize(QtCore.QSize(0, 40))
        self.pb_manual.setObjectName("pb_manual")
        self.horizontalLayout_6.addWidget(self.pb_manual)
        self.pb_auto = QtWidgets.QPushButton(self.tab_termostat)
        self.pb_auto.setMinimumSize(QtCore.QSize(0, 40))
        self.pb_auto.setObjectName("pb_auto")
        self.horizontalLayout_6.addWidget(self.pb_auto)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_termostat, "")
        self.schedules_tab = QtWidgets.QWidget()
        self.schedules_tab.setEnabled(False)
        self.schedules_tab.setObjectName("schedules_tab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.schedules_tab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(self.schedules_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(170, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 168, 288))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.hl_slot_line = QtWidgets.QHBoxLayout()
        self.hl_slot_line.setObjectName("hl_slot_line")
        self.pb_splot_minus = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_splot_minus.sizePolicy().hasHeightForWidth())
        self.pb_splot_minus.setSizePolicy(sizePolicy)
        self.pb_splot_minus.setMinimumSize(QtCore.QSize(40, 40))
        self.pb_splot_minus.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pb_splot_minus.setObjectName("pb_splot_minus")
        self.hl_slot_line.addWidget(self.pb_splot_minus)
        self.toolButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(0, 40))
        self.toolButton.setCheckable(True)
        self.toolButton.setChecked(True)
        self.toolButton.setObjectName("toolButton")
        self.hl_slot_line.addWidget(self.toolButton)
        self.verticalLayout_6.addLayout(self.hl_slot_line)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.pb_plus_ = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_plus_.setMinimumSize(QtCore.QSize(40, 40))
        self.pb_plus_.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pb_plus_.setObjectName("pb_plus_")
        self.horizontalLayout_10.addWidget(self.pb_plus_)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        spacerItem6 = QtWidgets.QSpacerItem(20, 171, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_7.addWidget(self.scrollArea)
        self.line = QtWidgets.QFrame(self.schedules_tab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox = QtWidgets.QCheckBox(self.schedules_tab)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_4.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.schedules_tab)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_4.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.schedules_tab)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_4.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.schedules_tab)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_4.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.schedules_tab)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_4.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.schedules_tab)
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_4.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.schedules_tab)
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_4.addWidget(self.checkBox_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.schedules_tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.schedules_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 268, 288))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.hl_time_temp_line = QtWidgets.QHBoxLayout()
        self.hl_time_temp_line.setObjectName("hl_time_temp_line")
        self.timeEdit = QtWidgets.QTimeEdit(self.scrollAreaWidgetContents_2)
        self.timeEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.timeEdit.setObjectName("timeEdit")
        self.hl_time_temp_line.addWidget(self.timeEdit)
        self.spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 40))
        self.spinBox.setMaximum(32)
        self.spinBox.setProperty("value", 25)
        self.spinBox.setObjectName("spinBox")
        self.hl_time_temp_line.addWidget(self.spinBox)
        self.pb_minus_time = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pb_minus_time.setMinimumSize(QtCore.QSize(40, 40))
        self.pb_minus_time.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pb_minus_time.setObjectName("pb_minus_time")
        self.hl_time_temp_line.addWidget(self.pb_minus_time)
        self.pb_plus_time = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pb_plus_time.setMinimumSize(QtCore.QSize(40, 40))
        self.pb_plus_time.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pb_plus_time.setObjectName("pb_plus_time")
        self.hl_time_temp_line.addWidget(self.pb_plus_time)
        self.verticalLayout_5.addLayout(self.hl_time_temp_line)
        spacerItem8 = QtWidgets.QSpacerItem(20, 171, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_7.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.schedules_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_time = QtWidgets.QLabel(self.centralwidget)
        self.lb_time.setObjectName("lb_time")
        self.horizontalLayout.addWidget(self.lb_time)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.lb_status_vent = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_status_vent.setFont(font)
        self.lb_status_vent.setObjectName("lb_status_vent")
        self.horizontalLayout.addWidget(self.lb_status_vent)
        self.lb_status_ac = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_status_ac.setFont(font)
        self.lb_status_ac.setObjectName("lb_status_ac")
        self.horizontalLayout.addWidget(self.lb_status_ac)
        self.lb_status_hot = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_status_hot.setFont(font)
        self.lb_status_hot.setObjectName("lb_status_hot")
        self.horizontalLayout.addWidget(self.lb_status_hot)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_temp.setText(_translate("MainWindow", "25°C"))
        self.lb_humidity.setText(_translate("MainWindow", "40%"))
        self.lb_temp_target.setText(_translate("MainWindow", "25°C"))
        self.pb_up.setText(_translate("MainWindow", "🔺️"))
        self.pb_ac.setText(_translate("MainWindow", "❄️"))
        self.pb_off.setText(_translate("MainWindow", "Off"))
        self.pb_heat.setText(_translate("MainWindow", "🔥️"))
        self.pb_down.setText(_translate("MainWindow", "🔻️"))
        self.pb_manual.setText(_translate("MainWindow", "Manual"))
        self.pb_auto.setText(_translate("MainWindow", "Auto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_termostat), _translate("MainWindow", "Termostat"))
        self.pb_splot_minus.setText(_translate("MainWindow", "-"))
        self.toolButton.setText(_translate("MainWindow", "Week"))
        self.pb_plus_.setText(_translate("MainWindow", "+"))
        self.checkBox.setText(_translate("MainWindow", "Monday"))
        self.checkBox_2.setText(_translate("MainWindow", "Tuesday"))
        self.checkBox_3.setText(_translate("MainWindow", "Wednesday"))
        self.checkBox_4.setText(_translate("MainWindow", "Thursday"))
        self.checkBox_5.setText(_translate("MainWindow", "Friday"))
        self.checkBox_6.setText(_translate("MainWindow", "Saturday"))
        self.checkBox_7.setText(_translate("MainWindow", "Sunday"))
        self.spinBox.setSuffix(_translate("MainWindow", "°C"))
        self.pb_minus_time.setText(_translate("MainWindow", "-"))
        self.pb_plus_time.setText(_translate("MainWindow", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.schedules_tab), _translate("MainWindow", "Schedules"))
        self.lb_time.setText(_translate("MainWindow", "19:04"))
        self.lb_status_vent.setText(_translate("MainWindow", "🌀️"))
        self.lb_status_ac.setText(_translate("MainWindow", "❄️"))
        self.lb_status_hot.setText(_translate("MainWindow", "🔥️"))


