# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 387)
        MainWindow.setStyleSheet("QPushButton:checked { background-color: rgb(85, 87, 83); }\n"
"QWidget {\n"
"    background-color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(85, 87, 83);    \n"
"    border-color: rgb(136, 138, 133);\n"
"    color: rgb(250,250,250);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_termostat = QtWidgets.QWidget()
        self.tab_termostat.setObjectName("tab_termostat")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_termostat)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lb_temp = QtWidgets.QLabel(self.tab_termostat)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(80)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_temp.setFont(font)
        self.lb_temp.setObjectName("lb_temp")
        self.horizontalLayout_2.addWidget(self.lb_temp)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_humidity = QtWidgets.QLabel(self.tab_termostat)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lb_humidity.setFont(font)
        self.lb_humidity.setObjectName("lb_humidity")
        self.horizontalLayout_3.addWidget(self.lb_humidity)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lb_temp_target = QtWidgets.QLabel(self.tab_termostat)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lb_temp_target.setFont(font)
        self.lb_temp_target.setObjectName("lb_temp_target")
        self.horizontalLayout_3.addWidget(self.lb_temp_target)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.pb_up = QtWidgets.QPushButton(self.tab_termostat)
        self.pb_up.setMinimumSize(QtCore.QSize(40, 50))
        self.pb_up.setObjectName("pb_up")
        self.verticalLayout_2.addWidget(self.pb_up)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pb_ac = QtWidgets.QPushButton(self.tab_termostat)
        self.pb_ac.setMinimumSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pb_ac.setFont(font)
        self.pb_ac.setCheckable(True)
        self.pb_ac.setChecked(False)
        self.pb_ac.setFlat(False)
        self.pb_ac.setObjectName("pb_ac")
        self.horizontalLayout_5.addWidget(self.pb_ac)
        self.pb_off = QtWidgets.QPushButton(self.tab_termostat)
        self.pb_off.setMinimumSize(QtCore.QSize(40, 50))
        self.pb_off.setCheckable(True)
        self.pb_off.setObjectName("pb_off")
        self.horizontalLayout_5.addWidget(self.pb_off)
        self.pb_heat = QtWidgets.QPushButton(self.tab_termostat)
        self.pb_heat.setMinimumSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pb_heat.setFont(font)
        self.pb_heat.setCheckable(True)
        self.pb_heat.setObjectName("pb_heat")
        self.horizontalLayout_5.addWidget(self.pb_heat)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.pb_down = QtWidgets.QPushButton(self.tab_termostat)
        self.pb_down.setMinimumSize(QtCore.QSize(40, 50))
        self.pb_down.setObjectName("pb_down")
        self.verticalLayout_2.addWidget(self.pb_down)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_termostat, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_time = QtWidgets.QLabel(self.centralwidget)
        self.lb_time.setObjectName("lb_time")
        self.horizontalLayout.addWidget(self.lb_time)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.lb_status_vent = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_status_vent.setFont(font)
        self.lb_status_vent.setObjectName("lb_status_vent")
        self.horizontalLayout.addWidget(self.lb_status_vent)
        self.lb_status_ac = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_status_ac.setFont(font)
        self.lb_status_ac.setObjectName("lb_status_ac")
        self.horizontalLayout.addWidget(self.lb_status_ac)
        self.lb_status_hot = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_status_hot.setFont(font)
        self.lb_status_hot.setObjectName("lb_status_hot")
        self.horizontalLayout.addWidget(self.lb_status_hot)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_temp.setText(_translate("MainWindow", "25°C"))
        self.lb_humidity.setText(_translate("MainWindow", "40%"))
        self.lb_temp_target.setText(_translate("MainWindow", "25°C"))
        self.pb_up.setText(_translate("MainWindow", "🔺️"))
        self.pb_ac.setText(_translate("MainWindow", "❄️"))
        self.pb_off.setText(_translate("MainWindow", "Off"))
        self.pb_heat.setText(_translate("MainWindow", "🔥️"))
        self.pb_down.setText(_translate("MainWindow", "🔻️"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_termostat), _translate("MainWindow", "Termostat"))
        self.lb_time.setText(_translate("MainWindow", "19:04"))
        self.lb_status_vent.setText(_translate("MainWindow", "🌀️"))
        self.lb_status_ac.setText(_translate("MainWindow", "❄️"))
        self.lb_status_hot.setText(_translate("MainWindow", "🔥️"))


